services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: hotpog
      POSTGRES_USER: hotpog
      POSTGRES_PASSWORD: hotpog
    ports:
      - "5432:5432"
    volumes:
      - ./localdata/postgres:/var/lib/postgresql/data

  test_db:
    image: postgres:16
    environment:
      POSTGRES_DB: hotpog_test
      POSTGRES_USER: hotpog
      POSTGRES_PASSWORD: hotpog
    ports:
      - "5433:5432"
