services:
  test_db:
    image: postgres:16
    environment:
      POSTGRES_DB: hotpog
      POSTGRES_USER: hotpog
      POSTGRES_PASSWORD: hotpog
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
